### ISSUE TITLE
"Error: "\xC3" from ASCII-8BIT to UTF-8" when installing 

### ISSUE THREAD

**Issue by colindean** [Homebrew/homebrew-bundle#1043]
```
Skipping rsstail (no bottle for Linux)
Skipping rsstail (no bottle for Linux)
Error: "\xC3" from ASCII-8BIT to UTF-8
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/json/common.rb:286:in `encode'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/json/common.rb:286:in `generate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/json/common.rb:286:in `pretty_generate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:76:in `lock'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:64:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

```
$ cat Brewfile 
brew 'docker-compose'
brew 'rsstail'
```

Brand new elementaryOS installation today.

**Comment by colindean** [comment]
https://www.codetable.net/hex/c3 = `Ã`

**Comment by colindean** [comment]
Found it. I injected pretty print right before the call to `JSON.pretty_generate(lock)` in locker.rb:

```ruby
{"entries"=>
  {"brew"=>
    {"docker-compose"=>
      {:version=>"2.2.3",
       :bottle=>
        {:rebuild=>0,
         :root_url=>"https://ghcr.io/v2/homebrew/core",
         :files=>
          {:arm64_monterey=>
            {:cellar=>":any_skip_relocation",
             :url=>
              "https://ghcr.io/v2/homebrew/core/docker-compose/blobs/sha256:1cccd370674458075325d199f4ebcabe3a34824a6dbad8346b96cdabda1fd0a9",
             :sha256=>
              "1cccd370674458075325d199f4ebcabe3a34824a6dbad8346b96cdabda1fd0a9"},
           :arm64_big_sur=>
            {:cellar=>":any_skip_relocation",
             :url=>
              "https://ghcr.io/v2/homebrew/core/docker-compose/blobs/sha256:1cccd370674458075325d199f4ebcabe3a34824a6dbad8346b96cdabda1fd0a9",
             :sha256=>
              "1cccd370674458075325d199f4ebcabe3a34824a6dbad8346b96cdabda1fd0a9"},
           :monterey=>
            {:cellar=>":any_skip_relocation",
             :url=>
              "https://ghcr.io/v2/homebrew/core/docker-compose/blobs/sha256:af736ed84076648e371bd5016c0f511e3cad3670b2eb1e17f3a33d0ecdb69fb8",
             :sha256=>
              "af736ed84076648e371bd5016c0f511e3cad3670b2eb1e17f3a33d0ecdb69fb8"},
           :big_sur=>
            {:cellar=>":any_skip_relocation",
             :url=>
              "https://ghcr.io/v2/homebrew/core/docker-compose/blobs/sha256:af736ed84076648e371bd5016c0f511e3cad3670b2eb1e17f3a33d0ecdb69fb8",
             :sha256=>
              "af736ed84076648e371bd5016c0f511e3cad3670b2eb1e17f3a33d0ecdb69fb8"},
           :catalina=>
            {:cellar=>":any_skip_relocation",
             :url=>
              "https://ghcr.io/v2/homebrew/core/docker-compose/blobs/sha256:af736ed84076648e371bd5016c0f511e3cad3670b2eb1e17f3a33d0ecdb69fb8",
             :sha256=>
              "af736ed84076648e371bd5016c0f511e3cad3670b2eb1e17f3a33d0ecdb69fb8"},
           :x86_64_linux=>
            {:cellar=>":any_skip_relocation",
             :url=>
              "https://ghcr.io/v2/homebrew/core/docker-compose/blobs/sha256:d222b0d3495bf8dde607c3a721f1556d9e2749e6c83030d0665312f7713ab011",
             :sha256=>
              "d222b0d3495bf8dde607c3a721f1556d9e2749e6c83030d0665312f7713ab011"}}}}}},
 "system"=>
  {"linux"=>
    {"elementary OS 6.1 J\xC3\xB3lnir (jolnir)"=>
      {"HOMEBREW_VERSION"=>"3.3.9",
       "HOMEBREW_PREFIX"=>"/home/linuxbrew/.linuxbrew",
       "Homebrew/linuxbrew-core"=>"8bdba997f6c32cdd556b2ef21a619adf662f561a",
       "GCC"=>
        #<Version:0x0000000002880688
         @detected_from_url=false,
         @version="9.3.0">}}}}
```

https://github.com/Homebrew/homebrew-bundle/blob/407dafc7dbdacd1d897cfc79e8c3ab86a859ca71/lib/bundle/locker.rb#L72-L73

The return of `system_linux` there is an ASCII-8BIT encoded string.

**Comment by colindean** [comment]
If I try to make it UTF-8 with `version.encode("UTF-8")`, it dies with the same error. If I try `version.force_encoding("UTF-8")`, then I get an error about modifying a frozen string. If I do `version.dup.force_encoding("UTF-8")`, then it works. I can then drop in

```ruby
version = version.dup.force_encoding("UTF-8")
```

and I'm able to complete the `brew bundle` execution.

I don't think that's the right fix, though: I think the return value of `OS::Linux.os_version` should be UTF-8 encoded, right?

**Comment by gromgit** [comment]
According to https://github.com/Homebrew/brew/blob/7fc2159fcddd1deed70d2a7225d34750f080160b/Library/Homebrew/brew.sh#L314-L338, `LC_ALL` should be forced to a UTF-8 encoding. Perhaps it's not doing the expected on your system?

**Comment by colindean** [comment]
```
[21:47:35 colin@balance ~ ]
$ echo $LC_ALL

[21:47:41 colin@balance ~ ]
$ if [[ -n "${HOMEBREW_MACOS}" ]]
> then
>   if [[ "$(locale charmap)" != "UTF-8" ]]
>   then
>     export LC_ALL="en_US.UTF-8"
>   fi
> else
>   if ! command -v locale >/dev/null
>   then
>     export LC_ALL=C
>   elif [[ "$(locale charmap)" != "UTF-8" ]]
>   then
>     locales="$(locale -a)"
>     c_utf_regex='\bC\.(utf8|UTF-8)\b'
>     en_us_regex='\ben_US\.(utf8|UTF-8)\b'
>     utf_regex='\b[a-z][a-z]_[A-Z][A-Z]\.(utf8|UTF-8)\b'
>     if [[ ${locales} =~ ${c_utf_regex} || ${locales} =~ ${en_us_regex} || ${locales} =~ ${utf_regex} ]]
>     then
>       export LC_ALL="${BASH_REMATCH[0]}"
>     else
>       export LC_ALL=C
>     fi
>   fi
> fi
[21:47:56 colin@balance ~ ]
$ echo $LC_ALL

[21:51:50 colin@balance ~ ]
$ [[ ${locales} =~ ${c_utf_regex} ]]
[21:51:55 colin@balance ~ ]
$ echo $?
0
[21:51:56 colin@balance ~ ]
$ echo ${BASH_REMATCH[0]}
C.UTF-8
[21:52:27 colin@balance ~ ]
$ [[ ${locales} =~ ${en_us_regex} ]]
[21:52:50 colin@balance ~ ]
$ echo ${BASH_REMATCH[0]}
en_US.utf8
[21:52:54 colin@balance ~ ]
$ [[ ${locales} =~ ${utf_regex} ]]
[21:53:03 colin@balance ~ ]
$ echo ${BASH_REMATCH[0]}
bg_BG.utf8
```

**Comment by colindean** [comment]
In binary mode:

```
$ for i in C C.UTF-8 en_US.UTF-8 en_US.utf8; do LC_ALL="${i}" ruby -e 'p ENV["LC_ALL"]; p IO.popen("lsb_release -a", "rb").readlines.map(&:encoding)'; done
"C"
No LSB modules are available.
[#<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>]
"C.UTF-8"
No LSB modules are available.
[#<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>]
"en_US.UTF-8"
No LSB modules are available.
[#<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>]
"en_US.utf8"
No LSB modules are available.
[#<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>]
```

Without binary mode:

```
$ for i in C C.UTF-8 en_US.UTF-8 en_US.utf8; do LC_ALL="${i}" ruby -e 'p ENV["LC_ALL"]; p IO.popen("lsb_release -a", "r").readlines.map(&:encoding)'; done
"C"
No LSB modules are available.
[#<Encoding:US-ASCII>, #<Encoding:US-ASCII>, #<Encoding:US-ASCII>, #<Encoding:US-ASCII>]
"C.UTF-8"
No LSB modules are available.
[#<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>]
"en_US.UTF-8"
No LSB modules are available.
[#<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>]
"en_US.utf8"
No LSB modules are available.
[#<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>]
```

**Comment by colindean** [comment]
IO.popen allows [explicitly setting the expected encoding](https://ruby-doc.org/core-2.7.0/IO.html#method-c-popen): 
```
for i in C C.UTF-8 en_US.UTF-8 en_US.utf8; do LC_ALL="${i}" ruby -e 'p ENV["LC_ALL"]; p IO.popen("lsb_release -a", "rb", external_encoding: "UTF-8").readlines.map(&:encoding)'; done
"C"
No LSB modules are available.
[#<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>]
"C.UTF-8"
No LSB modules are available.
[#<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>]
"en_US.UTF-8"
No LSB modules are available.
[#<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>]
"en_US.utf8"
No LSB modules are available.
[#<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>]
```

I tried to dig through ruby's `io.c` to figure how how the encoding is determined but ~C hurts my brain~ I think I've been looking at a screen too long today to quickly find it.

**Comment by colindean** [comment]
I needed to read a bit more. It's [here](https://github.com/ruby/ruby/blob/0ca00e2cb74f9d07d27844d97c29c208caab95a7/io.c#L3836) but I'm stopping there... this is not a bug in Ruby, haha.
