### ISSUE TITLE
Error: undefined method `install_from_api?' for Homebrew::EnvConfig:Module

### ISSUE THREAD

**Issue by gruen-f** [Homebrew/homebrew-bundle#1071]
Doing as instructed:

```
$ brew bundle dump   
Error: undefined method `install_from_api?' for Homebrew::EnvConfig:Module
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/bundle.rb:43:in `cask_installed?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:52:in `casks'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:33:in `dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:20:in `build_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:29:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
Run `brew update-reset`, your Homebrew is outdated.

**Comment by gruen-f** [comment]
Appreciated!

(Moving from intel to M1… thank you for the quick and excellent response.)
