### ISSUE TITLE
brew bundle including `gpg` crashes with "No available formula" error

### ISSUE THREAD

**Issue by ymtszw** [Homebrew/homebrew-bundle#1125]
* `brew --version`
```
Homebrew 3.6.1-58-g7a14ae6
Homebrew/homebrew-core (git revision da4fe3ba5e5; last commit 2022-09-16)
Homebrew/homebrew-cask (git revision fd0e3d9d50; last commit 2022-09-17)
```
* OS: Ubuntu 20.04 on WSL2
* Reproducible Brewfile (at least in my environment)

```ruby
brew "gpg"
```

* Reported error:

```
Warning: '' formula is unreadable: No available formula with the name "/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/gpg".
Error: undefined method `map' for nil:NilClass
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:166:in `outdated_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:162:in `upgradable_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:154:in `formula_upgradable?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:20:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

### Situation

Our team's Brewfile includes `gpg`, and recently (like this week or so) `brew bundle` started to fail on Ubuntu 20.04 environment with the error above.
Actually `gpg` itself is installed on the environment, and even can be `brew reinstall`-ed fine. It seems to be `brew bundle` specific problem.
It says it has problems around Aliases, but changing `gpg` to canonical `gnupg` did not solved the issue.

Hope it can be reproduced and be looked into. Thanks in advance!

**Comment by ymtszw** [comment]
The error looks similar to the one reported in https://github.com/Homebrew/discussions/discussions/3660

**Comment by MikeMcQuaid** [comment]
The formula name is `gnupg`, use that instead. The relevant bug mentioned was fixed in https://github.com/Homebrew/brew/pull/13888
