### ISSUE TITLE
`brew bundle dump` error of uppercase/lowercase recognition of `gem-x` formulae build by `brew-gem` formulae

### ISSUE THREAD

**Issue by BingoKingo** [Homebrew/homebrew-bundle#1144]
```
Error: key not found: "gem-istats"
Did you mean?  "gem-iStats"
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:186:in `fetch'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:186:in `tsort_each_child'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:415:in `call'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:347:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:347:in `call'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:176:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:176:in `to_a'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:176:in `tsort'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:152:in `tsort'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:214:in `sort!'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:39:in `formulae_by_full_name'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:23:in `formulae'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:55:in `dump'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:19:in `build_brewfile'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:29:in `dump_brewfile'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/opt/homebrew/Library/Homebrew/brew.rb:97:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
You'll need to provide more information here. This is just a backtrace.

To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

May reopen when we get this information.
