### ISSUE TITLE
Error: undefined method `no_install_from_api?' for `Homebrew::EnvConfig:Module`

### ISSUE THREAD

**Issue by RaisinTen** [Homebrew/homebrew-bundle#1179]
This is the contents of `Brewfile`:
```ruby
brew "cmake"
brew "clang-format"
brew "shellcheck"
brew "node"
brew "hugo"
brew "doxygen"
brew "esbuild"
brew "typescript"
brew "rapidjson"
```

Running `brew bundle` fails like this:
```sh
==> Tapping homebrew/bundle
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 6983, done.        
remote: Counting objects:   0% (1/648)        
...
Resolving deltas:  99% (4037/4077)
Resolving deltas: 100% (4077/4077)
Resolving deltas: 100% (4077/4077), done.
Tapped 1 command (99 files, 2MB).
Installing cmake
Installing clang-format
Installing shellcheck
Installing node
Installing hugo
Installing doxygen
Installing esbuild
Installing typescript
Installing rapidjson
Error: undefined method `no_install_from_api?' for Homebrew::EnvConfig:Module
Did you mean?  no_install_upgrade?
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:145:in `system'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:150:in `system_macos'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:75:in `lock'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:64:in `install'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'

Exited with code exit status 1
```

This suddenly started failing today on the CircleCI jobs. 🤔

**Comment by RaisinTen** [comment]
https://github.com/Homebrew/homebrew-bundle/issues/1071#issuecomment-1081795968 tells me that it's an update related issue. Point to note that we have set the env var, `HOMEBREW_NO_AUTO_UPDATE`, to `1`. Removing that fixed the issue.
