### ISSUE TITLE
Brew bundle failing with "undefined method oldnames"

### ISSUE THREAD

**Issue by mauricioklein** [Homebrew/homebrew-bundle#1227]
## Environment

- Homebrew 4.0.9
- Linux 6.1.27-060127-generic (running on Gitpod)

## Description

Nothing changed in my setup, which was working smoothly for months.

Today, I started facing this error when running `brew bundle install`.

Installing taps directly with `brew install` works, which means the problem is restricted to Brew Bundle.

## Error

```
$ brew bundle --debug
```

```
Using homebrew/bundle
Using homebrew/core
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading ca-certificates from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading cmake from API
/usr/bin/env /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/git --version
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading ncurses from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading openssl@3 from API
Error: undefined method `oldnames' for #<Formulary::FormulaNamespaceAPI7254f6aafc64c401975b544e0163895f::CaCertificates:0x00000000058e88c0>
Did you mean?  oldname
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:160:in `formula_to_hash'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:111:in `add_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:38:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:38:in `formulae_by_full_name'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:23:in `formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:189:in `formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:173:in `outdated_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:169:in `upgradable_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:161:in `formula_upgradable?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:20:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:96:in `bundle'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

## Brew bundle file

```yaml
tap "homebrew/bundle"
tap "homebrew/core"

brew "zplug"
```

**Comment by mauricioklein** [comment]
After some investigation, I noticed that the problem is related to the `Zplug` tap.

Removing the last line from the brew bundle file above makes the error go away.

Strangely, if I run `brew install zplug`, the tap is installed correctly with no errors.

**Comment by colindean** [comment]
> Homebrew 4.0.9

Please update Homebrew. Latest is 4.0.28.

**Comment by mauricioklein** [comment]
Thanks, it works!
