### ISSUE TITLE
error while installing from file 

### ISSUE THREAD

**Issue by tarikkavaz** [Homebrew/homebrew-bundle#1261]
```
$ brew update

Already up-to-date.


$ brew upgrade



$brew bundle install --file=~/zshFiles/dump/Brewfile

Using buo/cask-upgrade
Using heroku/brew
Using homebrew/bundle
Using homebrew/cask
Using homebrew/cask-fonts
Using homebrew/cask-versions
Using homebrew/core
Using homebrew/services
Using mczachurski/wallpapper
Using webp
Using autoconf
Using automake
Using coreutils
...
Using wmaurer.change-case
Error: 767: unexpected token at '{
  "entries": {
    "tap": {
      "buo/cask-upgrade": {
        "revision": "e1aadd4c97203c0de552f0c0e00baee47604e2c7"
      },
      "heroku/brew": {
        "revision": "26afdc76a586ed3ed1a38f41a72133e2ff3a9a05"
      },
      "homebrew/bundle": {
        "revision": "73fe1415f01bc26ce4df0c4f52099ab1a0ef5b9d"
      },
      "homebrew/cask": {
<<<<<<< HEAD
        "revision": "b34b0034738640d85279ee8da268dbc84b5c3b32"
=======
        "revision": "0b47eeb7b300b6b2285c0fd3cc123e229fd1fb85"
>>>>>>> 7c036e55e8f14972df9ce67acb1d92e2fe43f330
      },
      "homebrew/cask-fonts": {
        "revision": "3bf62dfa4b04f21319683e806823f41b5f0df63f"
      },
      "homebrew/cask-versions": {
<<<<<<< HEAD
        "revision": "4e6dbe03701917e59c2daf6d61e794772fbf214f"
      },
      "homebrew/core": {
        "revision": "a416fc1102fb3db3d474dc60b1e1624cf0789321"
=======
        "revision": "4d28968eaede6ef63d4f72c52f711883d320e1ee"
      },
      "homebrew/core": {
        "revision": "8c6ad68b8f8bd0b65ffbfb0f6c5e22d27666ecaa"
>>>>>>> 7c036e55e8f14972df9ce67acb1d92e2fe43f330
      },
      "homebrew/services": {
        "revision": "f130d397efc2fd3d3c418839c84afce9a5c63e80"
      },
      "mczachurski/wallpapper": {
        "revision": "c75be587e8abea6a455d66e34764ac75c785d0df"
      }
    },
...
  "system": {
    "macos": {
      "monterey": {
        "HOMEBREW_VERSION": "4.1.17",
        "HOMEBREW_PREFIX": "/usr/local",
        "Homebrew/homebrew-core": "api",
        "CLT": "14.2.0.0.1.1668646533",
        "Xcode": "14.2",
        "macOS": "12.7.1"
      },
      "ventura": {
        "HOMEBREW_VERSION": "4.1.13",
        "HOMEBREW_PREFIX": "/opt/homebrew",
        "Homebrew/homebrew-core": "api",
        "CLT": "14.3.1.0.1.1683849156",
        "Xcode": "15.0",
        "macOS": "13.5.2"
      },
      "sonoma": {
        "HOMEBREW_VERSION": "4.1.17",
        "HOMEBREW_PREFIX": "/opt/homebrew",
        "Homebrew/homebrew-core": "api",
        "CLT": "15.0.0.0.1.1694021235",
        "Xcode": "15.0.1",
        "macOS": "14.0"
      }
    }
  }
}
'
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:38:in `lock'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:67:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:103:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

**Comment by jacobbednarz** [comment]
this looks like you've got a merge conflict markers in your Brewfile.lock. can you confirm that both your Brewfile and Brewfile.lock are free from merge conflicts?

**Comment by tarikkavaz** [comment]
> this looks like you've got a merge conflict markers in your Brewfile.lock. can you confirm that both your Brewfile and Brewfile.lock are free from merge conflicts?

oh yes, I was inspecting only my Brewfile. My Brewfile.lock had the conflict. Thanks Jacob
