### ISSUE TITLE
Brew bundle failing for some formulae `Error: wrong number of arguments (given 4, expected 3)`

### ISSUE THREAD

**Issue by convenient** [Homebrew/homebrew-bundle#1269]
```
$ brew --version
Homebrew 4.1.25-17-g4b90ac2
Homebrew/homebrew-core (git revision 3bf66777d5d; last commit 2023-12-12)
Homebrew/homebrew-cask (git revision 064494d792; last commit 2023-12-12)
```

```
$ cat Brewfile
tap "blackfireio/homebrew-blackfire"
brew "blackfire-php74"
```

```
$ brew bundle -vvv
Skipping install of blackfireio/blackfire tap. It is already installed.
Using blackfireio/blackfire
Error: wrong number of arguments (given 4, expected 3)
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/opt/homebrew/Library/Homebrew/formula.rb:204:in `initialize'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:89:in `block in create_validator_slow'
/opt/homebrew/Library/Taps/blackfireio/homebrew-blackfire/Abstract/abstract-blackfire-php-extension.rb:19:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:498:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:498:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:738:in `factory'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:89:in `block in create_validator_slow'
/opt/homebrew/Library/Homebrew/formula.rb:2019:in `[]'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:43:in `formulae_by_full_name'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/skipper.rb:12:in `skip?'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:39:in `block in install'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:103:in `bundle'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

The formula https://github.com/blackfireio/homebrew-blackfire/blob/master/Formula/blackfire-php74.rb and abstract https://github.com/blackfireio/homebrew-blackfire/blob/master/Abstract/abstract-blackfire-php-extension.rb

This used to work and I updated brew recently and started seeing this fail.

**Comment by MikeMcQuaid** [comment]
You need to report this to https://github.com/blackfireio/homebrew-blackfire. They are using private APIs that have, as expected, changed so the formula is broken.
