### ISSUE TITLE
Error: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by adam-h** [Homebrew/homebrew-bundle#136]
```
› brew bundle
Succeeded in tapping caskroom/cask
Succeeded in tapping caskroom/versions
Succeeded in tapping homebrew/bundle
Succeeded in tapping homebrew/versions
Succeeded in tapping homebrew/versions
Succeeded in installing zsh
Succeeded in installing zsh-completions
Succeeded in installing bash
Succeeded in installing ack
Succeeded in installing coreutils
Succeeded in installing moreutils
Succeeded in installing findutils
Succeeded in installing grc
Succeeded in installing imagemagick
Succeeded in installing jp2a
libcaca: XQuartz is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/xquartz

You can download from:
  https://xquartz.macosforge.org
imlib2: XQuartz is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/xquartz

You can download from:
  https://xquartz.macosforge.org
Error: Unsatisfied requirements failed this build.
Failed in installing libcaca
Succeeded in installing libgit2
Succeeded in installing openssl
Succeeded in installing readline
Succeeded in installing ruby-build
Succeeded in installing rbenv
Succeeded in installing gnu-sed
Succeeded in installing wget
Succeeded in installing vim
Succeeded in installing homebrew/dupes/grep
Succeeded in installing homebrew/dupes/screen
Succeeded in installing git
Error: no implicit conversion of Symbol into Integer
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:18:in `fetch'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:18:in `initialize'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:10:in `new'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:10:in `install'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:56:in `block in install'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:40:in `each'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:40:in `install'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `run'
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:67:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:69:in `require?'
/usr/local/Library/brew.rb:149:in `<main>'
```

**Comment by adam-h** [comment]
Found the cause, but it would be good to be warned of the actual issue.

I had:

    brew 'imagemagick', ['with-webp']

When I needed:

    brew 'imagemagick', args: ['with-webp']

**Comment by mikemcquaid** [comment]
Not quite sure how to handle bad arguments like this. @xu-cheng, thoughts?

**Comment by xu-cheng** [comment]
See  #138

**Comment by adam-h** [comment]
:+1:
