### ISSUE TITLE
brew bundle doesn't work with the "new brew cask style"

### ISSUE THREAD

**Issue by voelzmo** [Homebrew/homebrew-bundle#137]
I switched to the new style for brew cask (see [the homebrew-cask readme](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system)) and now `brew bundle dump` doesn't work anymore:

```
$ brew bundle dump --force
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:843:in `keg_only?'
/usr/local/Library/Homebrew/formula.rb:1242:in `to_hash'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:59:in `block in formulae_info'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:59:in `map'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:59:in `formulae_info'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:13:in `formulae'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:30:in `cask_requirements'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:18:in `dump_brewfile'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:4:in `run'
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:69:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:69:in `require?'
/usr/local/Library/brew.rb:149:in `<main>'
```

**Comment by voelzmo** [comment]
Turns out, this has nothing to with `brew cask`, due to an update to El Capitan, the commandline tools were missing. Fixed it with `xcode-select --install` and installed them manually.
