### ISSUE TITLE
File path formulas break install

### ISSUE THREAD

**Issue by shanesmith** [Homebrew/homebrew-bundle#1460]
Adding a file path formula to `Brewfile` (ex: `brew "./path/to/foo.rb"`) makes `brew bundle install` fail with the following error:

```
Error: No available formula with the name "foo".
/opt/homebrew/Library/Homebrew/formulary.rb:898:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:1016:in `factory'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11558/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11558/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11558/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/formula.rb:2213:in `[]'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:190:in `linked?'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:198:in `unlinked_and_keg_only?'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:102:in `link_change_state!'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:49:in `install'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:16:in `install'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:50:in `block in install'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:12:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:12:in `install'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:135:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

From my quick research it seems the issue was introduced in https://github.com/Homebrew/homebrew-bundle/pull/1455.

I have noticed that installing file path formulas will [soon be deprecated](https://github.com/Homebrew/brew/pull/18436), but since they're still supported I figured an issue would be warranted.

**Comment by jacobbednarz** [comment]
i'm unsure of the deprecation timeline, @carlocab or @MikeMcQuaid. any thoughts there? if this functionality is on the way out, it probably doesn't make sense fixing this to work for a short time.

**Comment by yelsa** [comment]
Yes that backtrace is definitely passing through methods only introduced in https://github.com/Homebrew/homebrew-bundle/pull/1455 . 
I can see how the prior logic would have allowed it to fall through `Bundle::BrewInstaller.self.formula_in_array?` (btw: always returning `false`, so behaviour probably wasn't right in some cases).
However, I'm a bit stuck at progressing further. No matter what I try I cannot replicate the above error - file path formulas just keep on working fine for me.

**Comment by carlocab** [comment]
The timeline is a little unclear since deprecating it properly requires fixing up `brew` internals (which does rely on loading formulae from paths, but only in a known-good/working context).

However: I recommend _not_ loading formulae from files. It's riddled with bugs when used outside of `brew` internals. Put them in a tap instead and reference it with the tap name, e.g. `brew "tap-owner/tap-name/formula-name"`.

You can create a tap with `brew tap-new tap-owner/tap-name` (e.g. `brew tap-new carlocab/extra`). If you don't want to use `tap-new`, or don't want a Git repository there, just do
```
mkdir -p "$(brew --repository)/Library/Taps/tap-owner/homebrew-tap-name/"{Formula,Casks}
```
and then put the formulae/casks in the `Formula` and `Casks` directories respectively.

**Comment by jacobbednarz** [comment]
in that case @carlocab, unless we have strong objections, i would lean towards not supporting this to align closer with `brew` and save one more spot to deprecate it.

**Comment by carlocab** [comment]
No objections from here! Seems simplest to avoid adding code that we're only going to have to deprecate later.

**Comment by MikeMcQuaid** [comment]
Yes, sorry, this is a WONTFIX. If this every worked before it was accidental.
