### ISSUE TITLE
syntax error, unexpected tIDENTIFIER, expecting end-of-input

### ISSUE THREAD

**Issue by caitlin** [Homebrew/homebrew-bundle#155]
On a fresh install of Capitan 10.11.2, on Homebrew 0.9.5 (git revision 182f; last commit 2016-03-02).

```
Error: (eval):35: syntax error, unexpected tIDENTIFIER, expecting end-of-input
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:29:in `instance_eval'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:29:in `process'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:21:in `initialize'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `new'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `run'
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:67:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:21:in `require?'
/usr/local/Library/brew.rb:89:in `<main>'
```

**Comment by mikemcquaid** [comment]
What is the contents of your `Brewfile`?

**Comment by caitlin** [comment]
```
# Caitlin's Brewfile

# Necessary Stuff
install openssl
install redis
install mysql
install postgresql
install rbenv

# Install Cask
install caskroom/cask/brew-cask

# Install Casks

# Utilities
cask install alfred
cask install flux
cask install bartender
cask install fantastical
cask install dropbox
cask install omnifocus

# Development
cask install atom
cask install iterm2
cask install sequel-pro
cask install psequel
cask install github-desktop
cash install sketch

# Other apps
cask install slack
cask install evernote
cask install hazel
cask install 1password
cask install back blaze
```

**Comment by mikemcquaid** [comment]
@caitlin Sorry for the confusion but the syntax of `Brewfile`s changed a pretty long time ago now. Check out the README for the new format (e.g. `brew "openssl"` and `cask "slack"`) and shout if you need more help. Thanks!

**Comment by caitlin** [comment]
Oh, thanks! Looks like I was following an outdated tutorial.

**Comment by mikemcquaid** [comment]
@caitlin Can you link to it so I can get in touch? Thanks!

**Comment by caitlin** [comment]
https://mattstauffer.co/blog/setting-up-a-new-os-x-development-machine-part-2-global-package-managers
