### ISSUE TITLE
failure in initialization

### ISSUE THREAD

**Issue by mindyor** [Homebrew/homebrew-bundle#195]
Getting this syntax error upon `brew bundle` :

```
Error: (eval):47: syntax error, unexpected tIDENTIFIER, expecting end-of-input
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:29:in `instance_eval'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:29:in `process'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:21:in `initialize'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `new'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `run'
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:72:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:19:in `require?'
/usr/local/Library/Homebrew/brew.rb:90:in `<main>'
```

I'm sure I'm missing something simple, any ideas?

**Comment by MikeMcQuaid** [comment]
Please paste your `Brewfile` in here, thanks!

**Comment by mindyor** [comment]
https://github.com/mindyor/dotfiles/blob/master/osx/Brewfile

**Comment by MikeMcQuaid** [comment]
`cask 1password` on line 47 is invalid syntax. Fixing that will fix this.

**Comment by mindyor** [comment]
Oh, that _was_ silly. Thank you
