### ISSUE TITLE
syntax error, unexpected tCONSTANT, expecting end-of-input

### ISSUE THREAD

**Issue by dasilvacontin** [Homebrew/homebrew-bundle#203]
```
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Counting objects: 59, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 59 (delta 4), reused 22 (delta 0), pack-reused 0
Unpacking objects: 100% (59/59), done.
Checking connectivity... done.
Tapped 0 formulae (130 files, 148K)
Error: (eval):9: syntax error, unexpected tCONSTANT, expecting end-of-input
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:29:in `instance_eval'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:29:in `process'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:21:in `initialize'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `new'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:60:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

**Comment by dasilvacontin** [comment]
Issue was `cask install 1Password`, due to `1Password` beginning with a number. Fixed by changing it to `cask install '1Password'`.

The reported error is not user-friendly.

**Comment by MikeMcQuaid** [comment]
How would you suggest we improve it?

**Comment by dasilvacontin** [comment]
I later realised that apparently all package names are required to be strings (?).

I think the confusion came because of seeing lots of examples of the old `brew bundle` around the nets, which didn't require the quotes.

I think something like the following could be good:

```rb
Syntax Error: malformed Brewfile. Take a look at the examples – your rules should be similar:

  tap 'caskroom/cask' # for `brew tap caskroom/cask`
  tap 'telemachus/brew', 'https://telemachus@bitbucket.org/telemachus/brew.git'

  brew 'imagemagick' # for `brew install imagemagick`
  brew 'mysql', restart_service: true, conflicts_with: ['homebrew/versions/mysql56']
  brew 'emacs', args: ['with-cocoa', 'with-gnutls']

  cask 'google-chrome' # for `brew cask install google-chrome`
  cask_args appdir: '/Applications'
  cask 'java' unless system '/usr/libexec/java_home --failfast'
  cask 'firefox', args: { appdir: '~/my-apps/Applications' }

  # for `mas install 1Password`
  mas '1Password', id: 443987910
```

**Comment by MikeMcQuaid** [comment]
I'm passing on this because the README provides that example but I'll happily accept a PR that improves the messaging.
