### ISSUE TITLE
Topological sort failed pets and sundials

### ISSUE THREAD

**Issue by nilsdeppe** [Homebrew/homebrew-bundle#240]
Hi,

I'm attempting to use `brew bundle dump` to backup my Homebrew packages. However, when I do this I get the following error:

```
Error: topological sort failed: ["homebrew/science/petsc", "homebrew/science/sundials"]
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:152:in `block in tsort_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:180:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:135:in `tsort'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:151:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:18:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:33:in `cask_requirements'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:20:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:7:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:55:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

I'm following the directions in the error and filing a bug :)

Thanks for the awesome product!

Nils

**Comment by MikeMcQuaid** [comment]
Please paste your `Brewfile` here, thanks.

**Comment by MikeMcQuaid** [comment]
@nilsdeppe I need your `Brewfile` if you want me to help.

**Comment by nilsdeppe** [comment]
Hi Mike,

Sorry for the delay. I just checked a couple times and I cannot locate a `Brewfile` after running `brew bundle dump`. I also tried with the `--force` option. I'm assuming the file normally is created in the cwd, is that correct?

Nils

**Comment by MikeMcQuaid** [comment]
Can I see what your `brew list` outputs? Thanks!

**Comment by nilsdeppe** [comment]
Here it is:

```
autoconf                        libksba
automake                        libmpc
bash                            libmpc08
bash-completion2                libpng
bear                            libtiff
binutils                        libtool
boost                           libvo-aacenc
brew-cask                       libyaml
cairo                           little-cms2
chktex                          llvm
clang-format                    lua
clang-omp                       lynx
cloog                           mercurial
cloog-ppl015                    metis
cloog018                        mpfr
cmake                           mpfr2
cppcheck                        mumps
doxygen                         netcdf
eigen                           ninja
emacs                           open-mpi
ffmpeg                          openblas
fftw                            openmotif
fontconfig                      openssl
freetype                        p7zip
gcc                             pandoc
gcc46                           pango
gcc47                           parmetis
gcc48                           pcre
gd                              pdflib-lite
gdb                             perl
gdbm                            petsc
gettext                         pixman
ghostscript                     pkg-config
git                             ppl011
glew                            pstree
glib                            python
gmp                             python3
gmp4                            qt
gnuplot                         readline
gobject-introspection           reattach-to-user-namespace
google-benchmark                root
gource                          rtags
gperftools                      ruby
grace                           scalapack
graphviz                        sdl2
gsl                             sdl2_image
harfbuzz                        sqlite
hdf5                            sshfs
htop-osx                        suite-sparse
httpie                          sundials
hwloc                           superlu
hypre                           superlu43
icu4c                           superlu_dist
imagemagick                     szip
irssi                           tbb
isl                             terminal-notifier
isl011                          tmux
ispell                          unrar
jbig2dec                        valgrind
jpeg                            veclibfort
lame                            webp
lapack                          wget
libevent                        x264
libffi                          xrootd
libgpg-error                    xvid
libiomp                         xz
```
