### ISSUE TITLE
Error: undefined method `undent'

### ISSUE THREAD

**Issue by jschank** [Homebrew/homebrew-bundle#347]
Hi,
I ran brew cask cleanup
and brew cask cleanup

One of them returned an error with undent

and homebrew asked me to report the error. 
so here it is :)

```
Error: undefined method `undent' for #<String:0x0000000102c8a160>
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/opt/sonar-runner/.brew/sonar-runner.rb:23:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1591:in `to_hash'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:89:in `block in formulae_info'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:89:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:89:in `formulae_info'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:18:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:40:in `cask_requirements'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:22:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:63:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:18:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:106:in `<main>'

```

**Comment by jschank** [comment]
BTW, `$ brew doctor` reports no problems

**Comment by MikeMcQuaid** [comment]
Do you mean you ran `brew bundle cleanup` or `brew bundle dump`?

**Comment by jschank** [comment]
Hi,
Sorry. I don't recall exactly... hampered by the fact that I use a script to update brew regularly...

    brew update
    brew upgrade
    brew cask cleanup
    brew cleanup

    brew bundle dump --force --file=~/Dropbox/Apps/"$hostname"_Brewfile

Those are the commands I run. One of them resulted in the exception.

So it looks like it was `$ brew bundle dump` to answer your question.

**Comment by MikeMcQuaid** [comment]
Thanks for answering. Should be fixed now.
