### ISSUE TITLE
Error: undefined method `[]=' for nil:NilClass

### ISSUE THREAD

**Issue by a-kinder** [Homebrew/homebrew-bundle#583]
got this error doing `brew bundle` with a Brewfile. 

```
Error: undefined method `[]=' for nil:NilClass
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:49:in `block in lock'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:27:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:27:in `lock'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:53:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:75:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/utils.rb:79:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:79:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
Can I see the `Brewfile`? Thanks!

**Comment by issyl0** [comment]
Could you provide your (or another) Brewfile so that we can reproduce this, please?

**Comment by a-kinder** [comment]
Sure, thanks for the quick reply! Here is a modified Brewfile that still fails with the bundle command.

```
brew "coreutils"
brew "automake"
brew "autoconf"
brew "openssl"
brew "libyaml"
brew "readline"
brew "libxslt"
brew "libtool"
brew "unixodbc"
brew "libtiff"
brew "ansible"
brew "awscli"
brew "bash"
brew "coreutils" # Provides sha1sum
brew "gawk"
brew "gettext", link: true
brew "pre-commit"
brew "rlwrap"
brew "watch"
brew "wget"
brew "yarn"
brew "fzf"
brew "bat"
brew "hub"
brew "jq"
brew "overmind"
brew "johanhaleby/kubetail/kubetail"
brew "pgloader"
brew "postgresql@11", link: true
brew "exiftool"
brew "gs", link: true
brew "imagemagick"
brew "asdf", system: "asdf plugin-add elixir && asdf plugin-add erlang && asdf plugin-add nodejs"
cask "aws-vault"
brew "vips"
cask "wkhtmltopdf"
brew "argyll-cms"
brew "mupdf-tools"
brew "ruby", link: true
```

running on OSX

**Comment by a-kinder** [comment]
appears to be specific to the `gs` package

**Comment by MikeMcQuaid** [comment]
Reproduced. See https://github.com/Homebrew/homebrew-bundle/pull/584
