### ISSUE TITLE
Error on cleanup after a --force

### ISSUE THREAD

**Issue by katelovescode** [Homebrew/homebrew-bundle#616]
Running `cleanup`, then `cleanup --force`, then `cleanup` again to make sure it worked, I keep getting this error, but only on the run just after `cleanup --force` - also seems like it's not actually cleaning up since those packages are still around after the `--force`.  I'd expect `heroku-node` to stay because `heroku` demands it but the others should be gone or have similar warnings?

```
$ brew bundle cleanup
Would uninstall formulae:
libgpg-error                      libksba                           zlib                              heroku/brew/heroku-node
Would untap:
homebrew/cask

$ brew bundle cleanup --force
Error: Refusing to uninstall /usr/local/Cellar/heroku-node/12.13.0
because it is required by heroku, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies libgpg-error libksba zlib heroku/brew/heroku-node
Uninstalled 4 formulae
Untapping homebrew/cask...
Untapped 1 command and 3494 casks (3,598 files, 3.9MB).

$ brew bundle cleanup        
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
warning: templates not found in /Users/katedonaldson/.git-templates
remote: Enumerating objects: 3606, done.
remote: Counting objects: 100% (3606/3606), done.
remote: Compressing objects: 100% (3598/3598), done.
remote: Total 3606 (delta 25), reused 541 (delta 6), pack-reused 0
Receiving objects: 100% (3606/3606), 1.21 MiB | 14.97 MiB/s, done.
Resolving deltas: 100% (25/25), done.
Error: 767: unexpected token at '==> Tapping homebrew/cask
Tapped 1 command and 3494 casks (3,598 files, 3.9MB).
[{"token":"docker","name":["Docker Desktop","Docker Community Edition","Docker CE"],"homepage":"https://www.docker.com/community-edition","url":"https://download.docker.com/mac/stable/40693/Docker.dmg","appcast":"https://download.docker.com/mac/stable/appcast.xml","version":"2.1.0.5,40693","sha256":"8f7098e72a672d3523ac3791096e14315a49c53da985ed8ba5156b2349ec1bda","artifacts":[{"delete":["/Library/PrivilegedHelperTools/com.docker.vmnetd","/private/var/tmp/com.docker.vmnetd.socket","$(brew --prefix)/bin/docker","$(brew --prefix)/bin/docker-compose","$(brew --prefix)/bin/docker-credential-desktop","$(brew --prefix)/bin/docker-credential-osxkeychain","$(brew --prefix)/bin/docker-machine","$(brew --prefix)/bin/hyperkit","$(brew --prefix)/bin/kubectl","$(brew --prefix)/bin/kubectl.docker","$(brew --prefix)/bin/notary","$(brew --prefix)/bin/vpnkit"],"launchctl":["com.docker.helper","com.docker.vmnetd"],"quit":"com.docker.docker","signal":{}},["Docker.app"],{"trash":["$(brew --prefix)/bin/docker-compose.backup","$(brew --prefix)/bin/docker-machine.backup","$(brew --prefix)/bin/docker.backup","~/Library/Application Scripts/com.docker.helper","~/Library/Caches/KSCrashReports/Docker","~/Library/Caches/com.docker.docker","~/Library/Caches/com.plausiblelabs.crashreporter.data/com.docker.docker","~/Library/Containers/com.docker.docker","~/Library/Containers/com.docker.helper","~/Library/Group Containers/group.com.docker","~/Library/Preferences/com.docker.docker.plist"],"rmdir":["~/Library/Caches/KSCrashReports","~/Library/Caches/com.plausiblelabs.crashreporter.data"],"signal":{}}],"caveats":null,"depends_on":{},"conflicts_with":null,"container":null,"auto_updates":true},{"token":"google-backup-and-sync","name":["Google Backup and Sync"],"homepage":"https://www.google.com/drive/download/","url":"https://dl.google.com/drive/InstallBackupAndSync.dmg","appcast":null,"version":"latest","sha256":"no_check","artifacts":[{"quit":"com.google.GoogleDrive","signal":{}},["Backup and Sync.app"],{"trash":["~/Library/Application Scripts/com.google.GoogleDrive.FinderSyncAPIExtension","~/Library/Application Support/Google/Drive","~/Library/Caches/com.google.GoogleDrive","~/Library/Containers/com.google.GoogleDrive.FinderSyncAPIExtension","~/Library/Cookies/com.google.GoogleDrive.binarycookies","~/Library/Group Containers/google_drive","~/Library/Preferences/com.google.GoogleDrive.plist"],"signal":{}}],"caveats":"Although google-backup-and-sync may be installed alongside google-drive-file-stream, you should not use the same account with both.\n\n  https://support.google.com/a/answer/7496409#allowboth\n","depends_on":{},"conflicts_with":{"cask":["google-photos-backup-and-sync"]},"container":null,"auto_updates":null},{"token":"google-chrome","name":["Google Chrome"],"homepage":"https://www.google.com/chrome/","url":"https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg","appcast":"https://omahaproxy.appspot.com/history?os=mac;channel=stable","version":"79.0.3945.88","sha256":"f0031ceb313f1f28b9b6f387cb2df4547b6c12fc70153c6a12a367747c2d0223","artifacts":[{"launchctl":["com.google.keystone.agent","com.google.keystone.daemon"],"signal":{}},["Google Chrome.app"],{"trash":["/Library/Caches/com.google.SoftwareUpdate.*","/Library/Google/Google Chrome Brand.plist","/Library/Google/GoogleSoftwareUpdate","~/Library/Application Support/Google/Chrome","~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.google.chrome.app.*.sfl*","~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.google.chrome.sfl*","~/Library/Caches/Google/Chrome","~/Library/Caches/com.google.Chrome","~/Library/Caches/com.google.Chrome.helper.*","~/Library/Caches/com.google.Keystone","~/Library/Caches/com.google.Keystone.Agent","~/Library/Caches/com.google.SoftwareUpdate","~/Library/Google/Google Chrome Brand.plist","~/Library/Google/GoogleSoftwareUpdate","~/Library/LaunchAgents/com.google.keystone.agent.plist","~/Library/Logs/GoogleSoftwareUpdateAgent.log","~/Library/Preferences/com.google.Chrome.plist","~/Library/Preferences/com.google.Keystone.Agent.plist","~/Library/Saved Application State/com.google.Chrome.app.*.savedState","~/Library/Saved Application State/com.google.Chrome.savedState","~/Library/WebKit/com.google.Chrome"],"rmdir":["/Library/Google","~/Library/Application Support/Google","~/Library/Caches/Google","~/Library/Google"],"signal":{}}],"caveats":null,"depends_on":{"macos":{">=":["10.10"]}},"conflicts_with":{"cask":["google-chrome-beta","google-chrome-dev"]},"container":null,"auto_updates":true},{"token":"iterm2","name":["iTerm2"],"homepage":"https://www.iterm2.com/","url":"https://iterm2.com/downloads/stable/iTerm2-3_3_7.zip","appcast":"https://iterm2.com/appcasts/final.xml","version":"3.3.7","sha256":"a993e66119b8ddf97e6b50a03a8aa6fbf3954f66a3f896a7503876c06702e724","artifacts":[["iTerm.app"],{"trash":["~/Library/Application Support/iTerm","~/Library/Application Support/iTerm2","~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.googlecode.iterm2.sfl*","~/Library/Caches/com.googlecode.iterm2","~/Library/Preferences/com.googlecode.iterm2.plist","~/Library/Saved Application State/com.googlecode.iterm2.savedState"],"signal":{}}],"caveats":null,"depends_on":{"macos":{">=":["10.12"]}},"conflicts_with":null,"container":null,"auto_updates":true},{"token":"java","name":["OpenJDK Java Development Kit"],"homepage":"https://openjdk.java.net/","url":"https://download.java.net/java/GA/jdk13.0.1/cec27d702aa74d5a8630c65ae61e4305/9/GPL/openjdk-13.0.1_osx-x64_bin.tar.gz","appcast":null,"version":"13.0.1,9:cec27d702aa74d5a8630c65ae61e4305","sha256":"593c5c9dc0978db21b06d6219dc8584b76a59c79d57e6ec1b28ad0d848a7713f","artifacts":[["jdk-13.0.1.jdk",{"target":"/Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk"}]],"caveats":null,"depends_on":{},"conflicts_with":null,"container":null,"auto_updates":null},{"token":"mysides","name":["mysides"],"homepage":"https://github.com/mosen/mysides","url":"https://github.com/mosen/mysides/releases/download/v1.0.1/mysides-1.0.1.pkg","appcast":"https://github.com/mosen/mysides/releases.atom","version":"1.0.1","sha256":"76946b8f7c5bf714125d75f1ada8140e034f05a9e288c73a7af445d76c2a5514","artifacts":[{"pkgutil":"com.github.mosen.mysides","signal":{}},"mysides-1.0.1.pkg (Pkg)"],"caveats":null,"depends_on":{},"conflicts_with":null,"container":null,"auto_updates":null},{"token":"postico","name":["Postico"],"homepage":"https://eggerapps.at/postico/","url":"https://eggerapps-downloads.s3.amazonaws.com/postico-1.5.10.zip","appcast":"https://eggerapps.at/postico/docs/?file=changelist.html","version":"1.5.10","sha256":"f0318ddfafa1d52438cc38e160507e8140f595576f829cd4c0b7ff1c4d1f6e1d","artifacts":[["Postico.app"],{"trash":["~/Library/Application Scripts/at.eggerapps.Postico","~/Library/Containers/at.eggerapps.Postico","~/Library/Preferences/at.eggerapps.Postico.plist","~/Library/Saved Application State/at.eggerapps.Postico.savedState"],"signal":{}}],"caveats":null,"depends_on":{},"conflicts_with":null,"container":null,"auto_updates":null},{"token":"slack","name":["Slack"],"homepage":"https://slack.com/","url":"https://downloads.slack-edge.com/mac_releases/Slack-4.2.0-macOS.zip","appcast":"https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://slack.com/ssb/download-osx","version":"4.2.0","sha256":"f531fac754cecb12c082e52e3fd5957eeeb0e804e8c44e43d81635aefe409016","artifacts":[{"quit":"com.tinyspeck.slackmacgap","signal":{}},["Slack.app"],{"trash":["~/Library/Application Scripts/com.tinyspeck.slackmacgap","~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.tinyspeck.slackmacgap.sfl*","~/Library/Application Support/Slack","~/Library/Caches/com.tinyspeck.slackmacgap","~/Library/Caches/com.tinyspeck.slackmacgap.ShipIt","~/Library/Containers/com.tinyspeck.slackmacgap","~/Library/Containers/com.tinyspeck.slackmacgap.SlackCallsService","~/Library/Cookies/com.tinyspeck.slackmacgap.binarycookies","~/Library/Group Containers/*.com.tinyspeck.slackmacgap","~/Library/Group Containers/*.slack","~/Library/Preferences/com.tinyspeck.slackmacgap.helper.plist","~/Library/Preferences/com.tinyspeck.slackmacgap.plist","~/Library/Saved Application State/com.tinyspeck.slackmacgap.savedState"],"signal":{}}],"caveats":null,"depends_on":{},"conflicts_with":null,"container":null,"auto_updates":true},{"token":"visual-studio-code","name":["Microsoft Visual Studio Code","VS Code"],"homepage":"https://code.visualstudio.com/","url":"https://update.code.visualstudio.com/1.41.1/darwin/stable","appcast":"https://vscode-update.azurewebsites.net/api/update/darwin/stable/VERSION","version":"1.41.1","sha256":"efb558da07adcdf7b5e69cabda2a8b9359855e9e6f7ae62b4e1db7eb975c98e4","artifacts":[["Visual Studio Code.app"],["/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"],{"trash":["~/Library/Application Support/Code","~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.microsoft.vscode.sfl*","~/Library/Caches/com.microsoft.VSCode","~/Library/Caches/com.microsoft.VSCode.ShipIt","~/Library/Preferences/com.microsoft.VSCode.helper.plist","~/Library/Preferences/com.microsoft.VSCode.plist","~/Library/Saved Application State/com.microsoft.VSCode.savedState","~/.vscode"],"signal":{}}],"caveats":null,"depends_on":{},"conflicts_with":null,"container":null,"auto_updates":true}]
'
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:30:in `formula_dependencies'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/cleanup.rb:78:in `formulae_to_uninstall'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/cleanup.rb:22:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:83:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:82:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'

$ brew bundle cleanup
Would uninstall formulae:
libgpg-error                      libksba                           zlib                              heroku/brew/heroku-node
Would untap:
homebrew/cask

$ brew bundle cleanup
Would uninstall formulae:
libgpg-error                      libksba                           zlib                              heroku/brew/heroku-node
Would untap:
homebrew/cask
```

**Comment by MikeMcQuaid** [comment]
What's in your `Brewfile`?
