### ISSUE TITLE
`brew bundle cleanup` fails

### ISSUE THREAD

**Issue by gsong** [Homebrew/homebrew-bundle#626]
This just started happening today:

```sh
$ brew bundle cleanup --force --global
Error: undefined method `force?' for ["--force", "--global"]:Array
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/cleanup.rb:24:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:83:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:82:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'
```

Same error if I just try to run `brew bundle cleanup --global` as well.

I've reset all the repos with `brew update-reset`.

homebrew-bundle is at latest `master` as of `dc16c62efeaca298c6e3565663192fbe0081a6aa`.

**Comment by gsong** [comment]
@MikeMcQuaid Thank you for the quick fix!
