### ISSUE TITLE
`brew bundle dump` failed

### ISSUE THREAD

**Issue by Maecenas** [Homebrew/homebrew-bundle#627]
I was using the `brew bundle dump --describe --force --file` every day but it failed now.

```bash
$ brew bundle dump
Error: undefined method `force?' for []:Array
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:11:in `can_write_to_brewfile?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:30:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:81:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:82:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'
```

I tried several fixes but all failed:
1. `brew vendor-install ruby`
2. `brew untap homebrew/homebrew-bundle && brew tap homebrew/homebrew-bundle`

<details><summary>Additional Information:</summary>

```bash
$ brew --version
Homebrew 2.2.3-4-gfc0777b
Homebrew/homebrew-core (git revision f2463; last commit 2020-01-14)
Homebrew/homebrew-cask (git revision 7585ed; last commit 2020-01-15)

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/anaconda3/bin/icu-config
  /usr/local/anaconda3/bin/krb5-config
  /usr/local/anaconda3/bin/freetype-config
  /usr/local/anaconda3/bin/xslt-config
  /usr/local/anaconda3/bin/libpng16-config
  /usr/local/anaconda3/bin/python3.7-config
  /usr/local/anaconda3/bin/libpng-config
  /usr/local/anaconda3/bin/xml2-config
  /usr/local/anaconda3/bin/python3.7m-config
  /usr/local/anaconda3/bin/python3-config
  /usr/local/anaconda3/bin/curl-config
  /usr/local/anaconda3/bin/ncursesw6-config
  /usr/local/anaconda3/bin/pcre-config
```
</details>

**Comment by MikeMcQuaid** [comment]
Also fixed by https://github.com/Homebrew/homebrew-bundle/pull/628
