### ISSUE TITLE
Flakey failure for MAS installer

### ISSUE THREAD

**Issue by jacobbednarz** [Homebrew/homebrew-bundle#664]
Steps to reproduce:

1. Checkout `master`. 491180c6f8bbd2b1496ab25aee4889b7c3de8caf at the time of raising the issue.
1. Run `bundle exec rspec spec --seed 60330`. See consistent failures. 
1. Run `bundle exec rspec spec --seed 11827`. See consistent test suite passes.

```
Failures:

  1) Bundle::MacAppStoreInstaller when mas is installed when mas is not signed in tries to sign in with mas
     Failure/Error: expect { do_install }.to raise_error(RuntimeError)
       expected RuntimeError but nothing was raised
     # ./spec/bundle/mac_app_store_installer_spec.rb:64:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:67:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:67:in `block (2 levels) in <top (required)>'

Finished in 11.88 seconds (files took 0.20816 seconds to load)
213 examples, 1 failure

Failed examples:

rspec ./spec/bundle/mac_app_store_installer_spec.rb:61 # Bundle::MacAppStoreInstaller when mas is installed when mas is not signed in tries to sign in with mas
```

Reproducible on Mac OS 10.14.6

**Comment by colindean** [comment]
I'm able to reproduce this, too. I couldn't make heads or tails of it in the ~30 minutes I investigated it.

**Comment by jacobbednarz** [comment]
Now that the whalebrew support has landed, I'll try to look into this one shortly.

**Comment by jacobbednarz** [comment]
Minimum reproduction case is 

```
rspec ./spec/bundle/mac_app_store_dumper_spec.rb[1:3:1] ./spec/bundle/mac_app_store_installer_spec.rb[1:4:2:1] ./spec/bundle_utils_spec.rb[1:1:1,1:1:2,1:2:1,1:2:2] --seed 60330
```
