### ISSUE TITLE
Error: undefined method `named' for #<OptionsParser:0x00007f84742574e8>

### ISSUE THREAD

**Issue by loganjhennessy** [Homebrew/homebrew-bundle#754]
When attempting to run a `brew bundle dump`, I get the following error.

```
[~]$ brew bundle dump
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 4969 (delta 37), reused 46 (delta 19), pack-reused 4868
Receiving objects: 100% (4969/4969), 1.11 MiB | 1.85 MiB/s, done.
Resolving deltas: 100% (2884/2884), done.
Tapped 1 command (104 files, 1.5MB).
Error: undefined method `named' for #<OptionParser:0x00007f84742574e8>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:88:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

Reporting the bug as requested by the output. Please let me know if I can provide any other information about my system/configuration that might be helpful.

**Comment by colindean** [comment]
Thank you for reporting. See for resolution: https://github.com/Homebrew/homebrew-bundle/issues/751. In short, run `brew update` before running `brew bundle` to ensure you have the latest version.
