### ISSUE TITLE
`brew cask info` deprecation warning when calling `brew bundle`

### ISSUE THREAD

**Issue by carlocab** [Homebrew/homebrew-bundle#819]
This doesn't look intentional:

```
❯ brew bundle cleanup
Warning: Calling brew cask info is deprecated! Use brew info [--cask] instead.
Would uninstall formulae:
```

Is this a bug?

I know very little Ruby, or else I'd have offered a PR with a fix myself. Apologies for that. I am happy to try my hand at a PR if someone points me in the right direction, however.

**Comment by jacobbednarz** [comment]
What version are you running? I _think_ this may already be addressed in 848b0e0c3c228c118947b42cd74f9595a742fdd8.

**Comment by jacobbednarz** [comment]
Ah, actually, we may still have an outstanding reference at https://github.com/Homebrew/homebrew-bundle/blob/b84d4569eafe799c7c46c6c12c63215cb8095b6d/lib/bundle/cask_dumper.rb#L29

**Comment by carlocab** [comment]
Oh whoops. I knew I was forgetting important info in my first post. Sorry!

```
❯ brew config
HOMEBREW_VERSION: 2.5.11-235-g4b1ef4e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4b1ef4e41bae6c6ff9ae7284af791b3d862f98b4
Last commit: 25 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 26e0b4eb176370a3ff6f8107dca31f6ea06e7f7b
Core tap last commit: 23 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_COLOR: set
HOMEBREW_EDITOR: nvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: N/A
```

I have `launchd` running `brew update` daily, though, so I don't think that commit covers it. Let me know if there's anything else I can do to help.

**Comment by jacobbednarz** [comment]
Odd, we seem to running the same version but my `brew cask cleanup` doesn't give that deprecation. Perhaps I'm missing something but either way I'll put up this PR anyway to clean up those last references and it may fix it.

**Comment by carlocab** [comment]
That is odd. Does the Ruby version matter? That's the only other thing I can think of that might affect things. (`gem check` also complains a lot for me, though I've never figured out how to fix that. Is that even relevant? ...I don't use Ruby, as you can probably tell.)

I also tried `brew untap homebrew/bundle && brew tap homebrew/bundle && brew bundle cleanup`, and that didn't change anything.

**Comment by jacobbednarz** [comment]
I've just merged the #820; would you mind updating and let me know if you still have the issue?

**Comment by carlocab** [comment]
It's worse. :(

```
❯ brew bundle cleanup
Usage: brew info [options] [formula|cask]

Display brief statistics for your Homebrew installation.

If a formula or cask is provided, show summary of information about it.

      --analytics                  List global Homebrew analytics data or, if
                                   specified, installation and build error
                                   data for formula (provided neither
                                   HOMEBREW_NO_ANALYTICS nor
                                   HOMEBREW_NO_GITHUB_API are set).
      --days                       How many days of analytics data to
                                   retrieve. The value for days must be
                                   30, 90 or 365. The default is 30.
      --category                   Which type of analytics data to retrieve.
                                   The value for category must be install,
                                   install-on-request or build-error;
                                   cask-install or os-version may be
                                   specified if formula is not. The default
                                   is install.
      --github                     Open the GitHub source page for formula
                                   in a browser. To view formula history
                                   locally: brew log -p formula
      --json                       Print a JSON representation. Currently the
                                   default value for version is v1 for
                                   formula. For formula and cask use
                                   v2. See the docs for examples of using
                                   the JSON output:
                                   https://docs.brew.sh/Querying-Brew
      --installed                  Print JSON of formulae that are currently
                                   installed.
      --all                        Print JSON of all available formulae.
  -v, --verbose                    Show more verbose analytics data for
                                   formula.
      --formula, --formulae        Treat all named arguments as formulae.
      --cask, --casks              Treat all named arguments as casks.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -h, --help                       Show this message.

Error: Invalid usage: cannot specify --cask with --json=v1!
Warning: Failed to parse `brew info --cask --json`: 767: unexpected token at ''
Would uninstall formulae:
```

**Comment by carlocab** [comment]
I think `--json=v1` has been deprecated: https://github.com/MikeMcQuaid/brew/blob/311c10636b0e5a86b7042d745afe782b19ed4659/Library/Homebrew/cmd/info.rb#L181

**Comment by jacobbednarz** [comment]
😞 I'm still not getting the error locally. It looks like something is missing after `brew info --cask` though. Are you able to crank up the verbosity to see what is happening there?

**Comment by carlocab** [comment]
Wasn't sure how to crank up the verbosity (does `-vvv` work?), so I tried
```
❯ HOMEBREW_VERBOSE=1 brew bundle cleanup
Checking if we need to fetch /usr/local/Homebrew...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/carlocab/homebrew-personal...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/cowsay-org/homebrew-cowsay...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/eth-p/homebrew-software...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/martido/homebrew-graph...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/teamookla/homebrew-speedtest...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/universal-ctags/homebrew-universal-ctags...
Usage: brew info [options] [formula|cask]

Display brief statistics for your Homebrew installation.

If a formula or cask is provided, show summary of information about it.

      --analytics                  List global Homebrew analytics data or, if
                                   specified, installation and build error
                                   data for formula (provided neither
                                   HOMEBREW_NO_ANALYTICS nor
                                   HOMEBREW_NO_GITHUB_API are set).
      --days                       How many days of analytics data to
                                   retrieve. The value for days must be
                                   30, 90 or 365. The default is 30.
      --category                   Which type of analytics data to retrieve.
                                   The value for category must be install,
                                   install-on-request or build-error;
                                   cask-install or os-version may be
                                   specified if formula is not. The default
                                   is install.
      --github                     Open the GitHub source page for formula
                                   in a browser. To view formula history
                                   locally: brew log -p formula
      --json                       Print a JSON representation. Currently the
                                   default value for version is v1 for
                                   formula. For formula and cask use
                                   v2. See the docs for examples of using
                                   the JSON output:
                                   https://docs.brew.sh/Querying-Brew
      --installed                  Print JSON of formulae that are currently
                                   installed.
      --all                        Print JSON of all available formulae.
  -v, --verbose                    Show more verbose analytics data for
                                   formula.
      --formula, --formulae        Treat all named arguments as formulae.
      --cask, --casks              Treat all named arguments as casks.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -h, --help                       Show this message.

Error: Invalid usage: cannot specify --cask with --json=v1!
Warning: Failed to parse `brew info --cask --json`: 767: unexpected token at ''
Would uninstall formulae:
```
I could also do `HOMEBREW_DEBUT brew bundle cleanup`, but I'll need to dump that in a pastebin or something.

**Comment by carlocab** [comment]
Not sure if it helps, but it seems like I can get the same error from the shell using `brew info --cask $(brew list --cask) --json=v1`:

```
❯ brew info --cask $(brew list --cask) --json=v1
Usage: brew info [options] [formula|cask]

Display brief statistics for your Homebrew installation.

If a formula or cask is provided, show summary of information about it.

      --analytics                  List global Homebrew analytics data or, if
                                   specified, installation and build error
                                   data for formula (provided neither
                                   HOMEBREW_NO_ANALYTICS nor
                                   HOMEBREW_NO_GITHUB_API are set).
      --days                       How many days of analytics data to
                                   retrieve. The value for days must be
                                   30, 90 or 365. The default is 30.
      --category                   Which type of analytics data to retrieve.
                                   The value for category must be install,
                                   install-on-request or build-error;
                                   cask-install or os-version may be
                                   specified if formula is not. The default
                                   is install.
      --github                     Open the GitHub source page for formula
                                   in a browser. To view formula history
                                   locally: brew log -p formula
      --json                       Print a JSON representation. Currently the
                                   default value for version is v1 for
                                   formula. For formula and cask use
                                   v2. See the docs for examples of using
                                   the JSON output:
                                   https://docs.brew.sh/Querying-Brew
      --installed                  Print JSON of formulae that are currently
                                   installed.
      --all                        Print JSON of all available formulae.
  -v, --verbose                    Show more verbose analytics data for
                                   formula.
      --formula, --formulae        Treat all named arguments as formulae.
      --cask, --casks              Treat all named arguments as casks.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -h, --help                       Show this message.

Error: Invalid usage: cannot specify --cask with --json=v1!
```

However, doing the same with `brew info --cask $(brew list --cask) --json=v2` gives me the json output I suspect `brew bundle` is looking for.

**Comment by jacobbednarz** [comment]
I'm not sure if the differences between v1 and v2 are that great that we could straight to it. @MikeMcQuaid @colindean @issyl0 any thoughts on `s/--json=v1/--json=v2` for this?

**Comment by rlbaker** [comment]
I'm also receiving this same error, happy to provide debug logs or anything if extra verification is needed.

The underlying `brew` error was added in ~7 hours ago by: https://github.com/Homebrew/brew/commit/311c10636b0e5a86b7042d745afe782b19ed4659

Actual line: https://github.com/Homebrew/brew/blame/6936f56b13cfea5d988ea3b3d5026027c707ed95/Library/Homebrew/cmd/info.rb#L181

**Comment by carlocab** [comment]
@rlbaker thanks for tracking that down -- I'm allergic to git so I wasn't able to manage.

**Comment by jacobbednarz** [comment]
Looking at the two instances of `json=v1` in the bundle codebase, we should be right to update it.

```
$ rg -F "json=v1"
lib/bundle/locker.rb
90:        name_bottles = JSON.parse(`brew info --json=v1 --installed --quiet`)

lib/bundle/cask_dumper.rb
29:      cask_info_response = `brew info --cask #{cask_list.join(" ")} --json=v1`

spec/bundle/locker_spec.rb
73:        allow(locker).to receive(:`).with("brew info --json=v1 --installed --quiet").and_return <<~EOS

spec/bundle/cask_dumper_spec.rb
60:          .with("brew info --cask foo --json=v1")
73:          .with("brew info --cask foo --json=v1")
86:          .with("brew info --cask foo bar --json=v1")
```

I'll chuck up a PR now and get some reviews to make sure we're heading in the right direction.

**Comment by jacobbednarz** [comment]
Can you try #821 and let me know how if that gets us there?

**Comment by rlbaker** [comment]
Running `brew bundle cleanup` on that branch is throwing:

```
Error: no implicit conversion of String into Integer
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:33:in `dig'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:33:in `block in formula_dependencies'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:32:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:32:in `flat_map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:32:in `formula_dependencies'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/cleanup.rb:71:in `formulae_to_uninstall'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/cleanup.rb:22:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:103:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

From: https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/cask_dumper.rb#L33

I'll dig out the exact JSON it's choking on shortly.

**Comment by rlbaker** [comment]
Running `brew info --cask 1password --json=v2`

```json
{
  "formulae": [],
  "casks": [
    {
      "token": "1password",
      "name": [
        "1Password"
      ],
      "desc": "Password manager that keeps all passwords secure behind one password",
      "homepage": "https://1password.com/",
      "url": "https://c.1password.com/dist/1P/mac7/1Password-7.7.zip",
      "appcast": "https://app-updates.agilebits.com/product_history/OPM7",
      "version": "7.7",
      "sha256": "14617fe50edcdaf3d3fbfc06bb456e6d2e301ec7378189a1266d8517027b1fd5",
      "artifacts": [
        [
          "1Password 7.app"
        ],
        {
          "trash": [
            "~/Library/Application Scripts/*.agilebits.onepassword*",
            "~/Library/Containers/*.agilebits.onepassword*",
            "~/Library/Group Containers/2BUA8C4S2C.com.agilebits",
            "~/Library/Logs/1Password",
            "~/Library/Preferences/com.agilebits.onepassword*"
          ],
          "signal": {}
        }
      ],
      "caveats": null,
      "depends_on": {
        "macos": {
          ">=": [
            "10.13"
          ]
        }
      },
      "conflicts_with": {
        "cask": [
          "1password-beta"
        ]
      },
      "container": null,
      "auto_updates": true
    }
  ]
}
```

**Comment by carlocab** [comment]
Same error; posted it on the PR. Didn't realise @rlbaker had already gotten to it here.

It's getting late quite here, so I'll need to check back in in the morning. Apologies for dropping out in the middle of this.

**Comment by rlbaker** [comment]
Here's the JSON that's being output:

[raw](https://gist.github.com/rlbaker/10e7025eb68fbe673439132140146418#file-raw-json)
[formatted](https://gist.github.com/rlbaker/10e7025eb68fbe673439132140146418#file-formatted-json)
[gron](https://gist.github.com/rlbaker/10e7025eb68fbe673439132140146418#file-gron)

**Comment by carlocab** [comment]
Thanks for fixing this!
