### ISSUE TITLE
Error running brew bundle

### ISSUE THREAD

**Issue by rockshassa** [Homebrew/homebrew-bundle#886]
brewfile looks like: 
```
brew "clang-format"
brew "swiftlint"
brew "git-lfs"
```
NOTE: there is NO newline at the end of the brewfile

`brew bundle` error looks like: (this is in Circle CI)
```
Distillers-Mac-3:project distiller$ brew bundle
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 5595 (delta 11), reused 10 (delta 2), pack-reused 5563
Receiving objects: 100% (5595/5595), 1.26 MiB | 8.72 MiB/s, done.
Resolving deltas: 100% (3266/3266), done.
Tapped 1 command (108 files, 1.6MB).
Error: undefined method `exclude?' for "git-lfs":String
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:192:in `block in sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:191:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:191:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:21:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:52:in `formula_names'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:138:in `installed_formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:121:in `formula_installed?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:166:in `installed?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:36:in `install_change_state!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:27:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:12:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:35:in `block in install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

**Comment by colindean** [comment]
Are you running `brew update` before running `brew bundle`?

**Comment by rockshassa** [comment]
@colindean that seemed to fix it thanks. I guess CircleCI is serving a stale version at the moment. will close this.
