### ISSUE TITLE
brew bundle dump failed

### ISSUE THREAD

**Issue by markwu** [Homebrew/homebrew-bundle#891]
I just got the following error messages today and have no idea what's going on.

```
$ brew bundle dump
Error: undefined method `sub' for ["zh-TW"]:Array
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:45:in `block in dump_cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:44:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:44:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:44:in `dump_cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:36:in `block in dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:35:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:35:in `dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:20:in `build_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:32:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

Here comes my `brew config`:

```
$ brew config
HOMEBREW_VERSION: 2.7.6-11-g5b2f8a5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5b2f8a5a7307b58843eedfb2886a80964b937b30
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1fe981399a12641c22ac4860928e762c1d61236c
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.GL7lz2dMD9/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2
macOS: 10.15.7-x86_64
CLT: 12.0.32.28
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
```

**Comment by jacobbednarz** [comment]
It's choking at https://github.com/Homebrew/homebrew-bundle/blob/841ebf6db25b49bd2f65461a2d83ff16d8c7c9ed/lib/bundle/cask_dumper.rb#L45. What does `env | grep -i home` output for you? From your error, it looks to be an array which doesn't seem correct.

**Comment by Groupsun** [comment]
I also faced the same error when I attempt to export the x86 package by executing:

```
/usr/local/bin/brew bundle dump
```

And the same error logs came out:

```
Updating Homebrew...
Error: undefined method `exclude?' for "rubberband":String
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:192:in `block in sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:191:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:191:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:21:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:46:in `cask_requirements'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:19:in `build_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:32:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:120:in `<main>'
```

My `brew config`:

```
HOMEBREW_VERSION: 2.5.9
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: 2ed5d80ff2f8025823de9b9faacfca27fa006c80
Last commit: 3 months ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: cb7745ed470a8ecb865b8d9afe9af5a09ac70298
Core tap last commit: 3 months ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.tkAJkMgVyC/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit arrandale
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.5, 1.8.271.09, 1.8.0_231
macOS: 11.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

`env | grep -i home` output:

```
PATH=/opt/homebrew/bin:/Users/sunnychen/Tools:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/sunnychen/Documents/firrtl/utils/bin
HOME=/Users/sunnychen
HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
```

**Comment by markwu** [comment]
> It's choking at
> 
> https://github.com/Homebrew/homebrew-bundle/blob/841ebf6db25b49bd2f65461a2d83ff16d8c7c9ed/lib/bundle/cask_dumper.rb#L45
> 
> . What does `env | grep -i home` output for you? From your error, it looks to be an array which doesn't seem correct.

Here comes my env:

```
$ env | grep -i home
PHPBREW_HOME=/Users/markwu/.phpbrew
HOME=/Users/markwu
```

**Comment by markwu** [comment]
Okay, I think I found the problem. In the newest homebrew version, they support `--language`. Take libreoffice for example, after I install libreoffice, I also need to install libreoffice's `zh-TW` language pack with

```
brew install --cask --language=zh-TW libreoffice-language-pack
```

It seemdshomebrew-bundle does not recognize `--language` options.

That's why the dump stop at `Error: undefined method 'sub' for ["zh-TW"]:Array`.

**Comment by MikeMcQuaid** [comment]
> HOMEBREW_VERSION: 2.5.9
> ORIGIN: https://mirrors.ustc.edu.cn/brew.git

@Groupsun This is a very old version. Don't report bugs when using a custom origin.

**Comment by markwu** [comment]
@MikeMcQuaid Thanks, I confirm this issue fixed.

**Comment by MikeMcQuaid** [comment]
@markwu Good, I'm glad!
