### ISSUE TITLE
Error: protected method `declared_runtime_dependencies' with Swiftformat

### ISSUE THREAD

**Issue by joshdholtz** [Homebrew/homebrew-bundle#913]
Hello!

On of our CI jobs over at _fastlane_ (https://github.com/fastlane/fastlane/pull/18173) started failing with this error below when trying to install [SwiftFormat](https://formulae.brew.sh/formula/swiftformat)

The output told me to create an issue over here so that is what I’m doing 😇 

I was hoping that somebody would be able to help me determine if this is an error on my end or not! I appreciate your time helping me with this ❤️ 

```sh
brew bundle
➡️  Brew
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
Warning: Permanently added the RSA host key for IP address 'ip.address' to the list of known hosts.
Tapped 1 command (109 files, 1.7MB).
Error: protected method `declared_runtime_dependencies' called for #<Formulary::FormulaNamespace8dc1512549d8fbfb463670fa67223481::Swiftformat:0x00007f8b49297d28>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:147:in `formula_to_hash'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:114:in `add_formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:46:in `formulae_by_full_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:188:in `conflicts_with'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:198:in `resolve_conflicts!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:34:in `install_change_state!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:27:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:12:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:35:in `block in install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
rake aborted!
Command failed with status (1): [brew bundle...]
/Users/distiller/project/fastlane/swift/formatting/Rakefile:11:in `block in <top (required)>'
/Users/distiller/project/.bundle/ruby/2.5.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

```

**Comment by colindean** [comment]
I think https://github.com/Homebrew/homebrew-bundle/pull/907 fixed this. `brew update` and see if the problem persists.

**Comment by joshdholtz** [comment]
OMG... I totally searched for this and can't believe I didn't see that issue 🤦‍♂️

Thank you for the help!
