### ISSUE TITLE
`brew bundle dump` broken

### ISSUE THREAD

**Issue by adavidzh** [Homebrew/homebrew-bundle#918]
When updating, I usually use `brew bundle dump` to keep list of installed items up to date.

Recently, `brew bundle dump` started to croak with:
```
> brew bundle dump --file=- 
Error: key not found: "python@3.8"
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:180:in `fetch'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:180:in `tsort_each_child'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:180:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:180:in `tsort_each_child'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `to_a'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `tsort'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:152:in `tsort'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:208:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:39:in `formulae_by_full_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:23:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:55:in `dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:19:in `build_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:29:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

I'm not proficient in `ruby` and it is not clear to me what is going on.

**Comment by MikeMcQuaid** [comment]
@adavidzh Can you try to run `brew update` and tell me if you can still reproduce after that? If so, can I see you `Brewfile`, `brew bundle check --verbose` and `git -C $(brew --repo homebrew/bundle) log -1` output.

**Comment by adavidzh** [comment]
> @adavidzh Can you try to run `brew update` and tell me if you can still reproduce after that?

Confirmed.

So, let's go by parts:

> `brew bundle check --verbose`
```
> brew bundle check --verbose
Error: key not found: "python@3.8"
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:180:in `fetch'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:180:in `tsort_each_child'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:180:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:180:in `tsort_each_child'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `to_a'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `tsort'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:152:in `tsort'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:208:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:39:in `formulae_by_full_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:23:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:138:in `installed_formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:121:in `formula_installed?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:97:in `formula_installed_and_up_to_date?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_checker.rb:10:in `installed_and_up_to_date?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/checker.rb:28:in `block in full_check'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/checker.rb:28:in `reject'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/checker.rb:28:in `full_check'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/checker.rb:51:in `find_actionable'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/checker.rb:97:in `formulae_to_install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/checker.rb:78:in `block in check'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/checker.rb:76:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/checker.rb:76:in `public_send'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/checker.rb:76:in `check'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/check.rb:14:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:126:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

> `git -C $(brew --repo homebrew/bundle) log -1`

The hash is `28470a82c93ffb37275aa834594bcad3bf0af49e`.

> `Brewfile`

Since that has a lot of things and is the output (rather than the input) I'll just leave this here:
```
> grep python Brewfile
brew "python@3.9"
brew "boost-python3"
brew "ipython"
````

Indeed there is no `python@3.8` installed anymore and `brew doctor` does complain (I should have started here):
```
Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install python@3.8

Run `brew missing` for more details.
```

And `brew missing` then says
```
adwaita-icon-theme: python@3.8
atk: python@3.8
gsettings-desktop-schemas: python@3.8
libcroco: python@3.8
liblqr: python@3.8
links: python@3.8
suite-sparse: python@3.8
```

Looking at `suite-sparse`, I see no dependency on `python@3.8`:
```
> brew info suite-sparse
suite-sparse: stable 5.8.1 (bottled)
Suite of Sparse Matrix Software
https://people.engr.tamu.edu/davis/suitesparse.html
Conflicts with:
  mongoose (because suite-sparse vendors libmongoose.dylib)
/usr/local/Cellar/suite-sparse/5.8.1 (163 files, 45.9MB) *
  Poured from bottle on 2021-02-11 at 16:23:49
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/suite-sparse.rb
==> Dependencies
Build: cmake ✔
Required: metis ✔, openblas ✔, tbb ✔
==> Analytics
install: 10,839 (30 days), 35,993 (90 days), 217,757 (365 days)
install-on-request: 609 (30 days), 2,222 (90 days), 13,936 (365 days)
build-error: 0 (30 days)
```

After `brew reinstall suite-sparse`, `brew missing` seems content. So, I `brew reinstall`ed all of the `brew missing` and 

So, while I am not sure why `brew bundle` was unhappy, there was clearly something else going on.

Thanks for getting me on the right track. I'll close since this may have been a red herring.
