### ISSUE TITLE
brew bundle fails with Error: undefined method `bottle_hash' for 

### ISSUE THREAD

**Issue by armenzg** [Homebrew/homebrew-bundle#919]
This was [executed](https://github.com/getsentry/sentry/runs/1880327397) on Github (Ubuntu 20).
```
Run brew bundle
  brew bundle
  shell: /usr/bin/bash -e {0}
  env:
    PIP_DISABLE_PIP_VERSION_CHECK: on
    SHELL: /bin/zsh
    VOLTA_HOME: /home/runner/.volta
    PATH: /home/runner/.volta/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
##[debug]/usr/bin/bash -e /home/runner/work/_temp/7c8a5eac-8ca0-496f-bb07-93287df3d03b.sh
==> Tapping homebrew/bundle
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
Tapped 1 command (110 files, 1.8MB).
Error: undefined method `bottle_hash' for #<Formulary::FormulaNamespacef96ae88258095fec2b5f7c1fcd8315e5::Pyenv:0x000000000381a9b8>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:152:in `formula_to_hash'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:111:in `add_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:44:in `formulae_by_full_name'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:188:in `conflicts_with'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:198:in `resolve_conflicts!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:34:in `install_change_state!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:27:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:12:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:35:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by MikeMcQuaid** [comment]
Run `brew update`.
