### ISSUE TITLE
Unknown error running brew bundle in linuxbrew

### ISSUE THREAD

**Issue by stephengroat** [Homebrew/homebrew-bundle#921]
```
Run brew bundle
==> Tapping homebrew/bundle
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
Tapped 1 command (110 files, 1.8MB).
Error: undefined method `bottle_hash' for #<Formulary::FormulaNamespacec3faac258c4f5035b66134e247899449::Rbenv:0x0000000001d95b60>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:152:in `formula_to_hash'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:111:in `add_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:44:in `formulae_by_full_name'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:188:in `conflicts_with'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:198:in `resolve_conflicts!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:34:in `install_change_state!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:27:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:12:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:35:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
Error: Process completed with exit code 1.
```

brewfile
```
# frozen_string_literal: true

brew 'rbenv'
brew 'tfenv'
```

**Comment by MikeMcQuaid** [comment]
Run `brew update`.
