### ISSUE TITLE
Error: key not found 

### ISSUE THREAD

**Issue by ea2809** [Homebrew/homebrew-bundle#923]
When I run `brew bundle dump` there is a problem:

```
Error: key not found: "osx-cross/arm/arm-gcc-bin@8"
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:181:in `fetch'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:181:in `tsort_each_child'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:181:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:181:in `tsort_each_child'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `to_a'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `tsort'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:152:in `tsort'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:209:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:39:in `formulae_by_full_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:23:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:55:in `dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:19:in `build_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:29:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

I would love to give you more information, but I have no more.

Thanks for everything.

**Comment by ea2809** [comment]
After reviewing this issue, I have to say SORRY. Thanks for everything and sorry again.

arm-gcc-bin is not at osx-cross/homebrew-arm
