### ISSUE TITLE
`brew bundle dump` => "Error: key not found"

### ISSUE THREAD

**Issue by zx8** [Homebrew/homebrew-bundle#925]
```
$ brew --version
Homebrew 3.0.1-120-g5ca03ab
Homebrew/homebrew-core (git revision 297bd; last commit 2021-02-19)
Homebrew/homebrew-cask (git revision c170c; last commit 2021-02-19)
```
---

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
```

---

```sh
$ brew bundle dump
Error: key not found: "terraform"
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:181:in `fetch'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:181:in `tsort_each_child'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:181:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:181:in `tsort_each_child'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `to_a'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:176:in `tsort'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tsort.rb:152:in `tsort'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:209:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:39:in `formulae_by_full_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:23:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:55:in `dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:19:in `build_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:29:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

`terraform` was installed using https://github.com/hashicorp/homebrew-tap:

```sh
$ brew install hashicorp/tap/terraform
```

**Comment by gromgit** [comment]
What's the output of `brew readall`?

**Comment by zx8** [comment]
@gromgit No output from that command.

**Comment by gromgit** [comment]
Hmmm. What's the output of `brew config`?

**Comment by zx8** [comment]
```
HOMEBREW_VERSION: 3.0.1-120-g5ca03ab
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5ca03ab4e4fda9c8aaaef07400658627090bc453
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a28576adfa9c71055bfe40306fc1451c0491b4ac
Core tap last commit: 72 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Tp9K0NtsS5/org.macosforge.xquartz:0
HOMEBREW_EDITOR: subl -nw
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.32.29
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
Can I see the output of `brew uses hashicorp/tap/terraform` and `brew uses terraform`? Thanks!

**Comment by zx8** [comment]
```
$ brew uses hashicorp/tap/terraform
atlantis  cdktf  terraform-provider-libvirt  terraform-provisioner-ansible  terragrunt

$ brew uses terraform
atlantis  cdktf  terraform-provider-libvirt  terraform-provisioner-ansible  terragrunt
```

**Comment by MikeMcQuaid** [comment]
Thanks! `brew uses terraform --installed`?

**Comment by zx8** [comment]
```
$ brew uses terraform --installed
terragrunt
```

**Comment by zx8** [comment]
OK, so after running `brew uninstall terragrunt`, `brew bundle dump` works again, so that seems to be the problem here. 👍

**Comment by MikeMcQuaid** [comment]
@zx8 Glad you have a workaround here! This is still a 🐛 that I'd like to fix, though.
