### ISSUE TITLE
undefined method `bottle_hash'

### ISSUE THREAD

**Issue by ConfidantCommunications** [Homebrew/homebrew-bundle#958]
I attempted to install Hashlink and received a message saying to report a bug:
```
Error: undefined method `bottle_hash' for #<Formulary::FormulaNamespace32989b22062afdfbc5d2a1f83c408403::Cmake:0x00007fe02b9b8d28>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:152:in `formula_to_hash'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:111:in `add_formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:44:in `formulae_by_full_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:188:in `conflicts_with'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:198:in `resolve_conflicts!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:34:in `install_change_state!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:27:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:12:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:35:in `block in install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
```

**Comment by colindean** [comment]
After running `brew update`, try again. If it still happens, please provide the output of `brew config` and `brew doctor` a [gist](https://gist.github.com) and include the minimal `Brewfile` that reproduces the problem.

It would also help if you could enclose your explanation's log dump in a \``` code block.

**Comment by ConfidantCommunications** [comment]
Thanks—will try that. Sorry I don't delve into homebrew much. I edited the code formatting. Will report back asap.
