### ISSUE TITLE
there was a bug when i was performing brew bundle dump

### ISSUE THREAD

**Issue by wibus-wee** [Homebrew/homebrew-bundle#974]
`wibus@wibusdeiMac ~ % brew bundle dump`

then, it return

```bash
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:154:in `formula_to_hash'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:111:in `add_formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:38:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:38:in `formulae_by_full_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:23:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:55:in `dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:19:in `build_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:29:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'

```

**Comment by gromgit** [comment]
> then, it return

What is the output in between:
```
brew bundle dump
```
and:
```
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
```
?

**Comment by wibus-wee** [comment]
```bash
wibus@wibusdeiMac ~ % brew bundle dump
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (mongodb/brew).
==> New Formulae
mongodb/brew/mongodb-mongocryptd         mongodb/brew/mongodb-mongocryptd@4.2
==> Updated Formulae
Updated 2 formulae.

Error: undefined method `bottle_hash' for #<Formulary::FormulaNamespace592958f13892655fbf773c98b7dc73a3::PkgConfig:0x00007fc0ab11e928>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:154:in `formula_to_hash'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:111:in `add_formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:38:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:38:in `formulae_by_full_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:23:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:55:in `dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:19:in `build_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:29:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
```
## config
```bash
HOMEBREW_VERSION: 2.7.1
ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HEAD: fdb71a5cb3029da2ef74d7e09c40575bbfb4ec72
Last commit: 6 months ago
Core tap ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
Core tap HEAD: 7c6f18ebdedc74467d5394e733a9f0def7bfed07
Core tap last commit: 5 months ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.aliyun.com/homebrew/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_152, 1.8.0_151
macOS: 11.0.1-x86_64
CLT: N/A
Xcode: 12.4
```

## brew doctor

```bash
wibus@wibusdeiMac ~ % brew doctor     
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  mongosh
  unrar

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/v8-testing.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.9
```

I don't understand this 😂

thank you

**Comment by wibus-wee** [comment]
I used Homebrew sources from other places, it is very difficult to clone directly from GitHub in China, and sometimes I can't connect to GitHub RAW

**Comment by gromgit** [comment]
> I used Homebrew sources from other places, it is very difficult to clone directly from GitHub in China, and sometimes I can't connect to GitHub RAW

While I sympathise, the fact remains that Homebrew has no control over private mirrors, and since even the latest update leaves you __way__ behind mainline Homebrew:
```
$ brew config
HOMEBREW_VERSION: 3.1.12-15-gd3887df
ORIGIN: https://github.com/Homebrew/brew
HEAD: d3887df2a39d270c7988985c5bf9099c8229aeca
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ea4be0397191ca78addc257ee450de9174ae7c3e
Core tap last commit: 16 hours ago
Core tap branch: master
...
```
only the people running the Tsinghua University mirrors can help you in your current config, by bringing their mirrors up-to-date.

**Comment by wibus-wee** [comment]
this mean that I can't run the command because of the mirror?

thank you. and I want to ask another question

if I can't use this command, how I can make a brew backup?

**Comment by gromgit** [comment]
> this mean that I can't run the command because of the mirror?

Yes. You wouldn't get this error if you use the main GitHub URLs (unless something else was wrong).

> if I can't use this command, how I can make a brew backup?

`brew leaves` should actually list the same formulae as `brew bundle dump`. In theory, `brew install`ing that list should, after all necessary dependencies are auto-installed, cover all the formulae you have installed right now. It's not a bundle dump (which also covers casks, apps installed via `mas`, and taps), but it's at least something.

**Comment by wibus-wee** [comment]
thank
